{
  "formatVersion": "1.1",
  "component": {
    "group": "com.toddway",
    "module": "buildchecks",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "buildchecks-4.1.1.jar",
          "url": "buildchecks-4.1.1.jar",
          "size": 497817,
          "sha512": "ce5b98dae682f49a4c6f8635d34e35a5ec19e0feee476a3d68e22d8b21f7e85972826fec925bed6bcfa2c9e51323205d6b2656dacf8d5af546c51ba6eed769d1",
          "sha256": "c45b28160b3050828e76480db7a8fc236675804f6b11a4475d6785a706bc3ccd",
          "sha1": "2978d65c6384c03b54d97753e95c1299b7d3edc9",
          "md5": "16d75d02ab5865c48f5a53d7df01d715"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "5.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "buildchecks-4.1.1.jar",
          "url": "buildchecks-4.1.1.jar",
          "size": 497817,
          "sha512": "ce5b98dae682f49a4c6f8635d34e35a5ec19e0feee476a3d68e22d8b21f7e85972826fec925bed6bcfa2c9e51323205d6b2656dacf8d5af546c51ba6eed769d1",
          "sha256": "c45b28160b3050828e76480db7a8fc236675804f6b11a4475d6785a706bc3ccd",
          "sha1": "2978d65c6384c03b54d97753e95c1299b7d3edc9",
          "md5": "16d75d02ab5865c48f5a53d7df01d715"
        }
      ]
    }
  ]
}
