{
  "formatVersion": "1.1",
  "component": {
    "group": "com.toddway",
    "module": "buildchecks",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "buildchecks-4.0.6.jar",
          "url": "buildchecks-4.0.6.jar",
          "size": 386234,
          "sha512": "50db0899a2baeb366a652f6551d515ce01ef20a43a69314933edd341f53138af95d3621eb7312ec5e2bc79ecc7a36b1d44eb211704f2d017e858c8db5b659f04",
          "sha256": "ad499387feef048b81156b65907850363d30c28e1c4fb9155811702620638120",
          "sha1": "777096566072e699a6bcc3a140301496f7584d8c",
          "md5": "c38c122db55d1b28310387313fe1f658"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "5.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "buildchecks-4.0.6.jar",
          "url": "buildchecks-4.0.6.jar",
          "size": 386234,
          "sha512": "50db0899a2baeb366a652f6551d515ce01ef20a43a69314933edd341f53138af95d3621eb7312ec5e2bc79ecc7a36b1d44eb211704f2d017e858c8db5b659f04",
          "sha256": "ad499387feef048b81156b65907850363d30c28e1c4fb9155811702620638120",
          "sha1": "777096566072e699a6bcc3a140301496f7584d8c",
          "md5": "c38c122db55d1b28310387313fe1f658"
        }
      ]
    }
  ]
}
