{
  "formatVersion": "1.1",
  "component": {
    "group": "com.toddway",
    "module": "buildchecks",
    "version": "4.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "buildchecks-4.1.2.jar",
          "url": "buildchecks-4.1.2.jar",
          "size": 499417,
          "sha512": "1f6895d13d1f8a78e83b4f7b681c100128f9cce44cf686a1b6daa9e18ee26033ca96fbd78d7fb9c4392d4e083cd22a397c9b3b8e734fca8ba31f2eed7e8ddd6b",
          "sha256": "01bf2802520877620bdd1a1e55c382de7724a82d0222a7b9f572e3a2e4ab6fbb",
          "sha1": "89480b588047b2db4f272dff4be118171c3377c6",
          "md5": "c34b1a61625d341a39b13f67b91e19d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "5.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "buildchecks-4.1.2.jar",
          "url": "buildchecks-4.1.2.jar",
          "size": 499417,
          "sha512": "1f6895d13d1f8a78e83b4f7b681c100128f9cce44cf686a1b6daa9e18ee26033ca96fbd78d7fb9c4392d4e083cd22a397c9b3b8e734fca8ba31f2eed7e8ddd6b",
          "sha256": "01bf2802520877620bdd1a1e55c382de7724a82d0222a7b9f572e3a2e4ab6fbb",
          "sha1": "89480b588047b2db4f272dff4be118171c3377c6",
          "md5": "c34b1a61625d341a39b13f67b91e19d3"
        }
      ]
    }
  ]
}
