{
  "formatVersion": "1.1",
  "component": {
    "group": "com.toddway",
    "module": "buildchecks",
    "version": "4.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "buildchecks-4.0.4.jar",
          "url": "buildchecks-4.0.4.jar",
          "size": 384859,
          "sha512": "a93119dfe6af4b902ad364f48cb25e9105efe9f0a480793730a0e6a172137b4118a2a89011a8245cbad483f992586661aa1bbf72246b3d348389d683a61e4b17",
          "sha256": "352bd26ca61258123518304928f142b6c1fadef5671cf6c54a41f1a6b5774963",
          "sha1": "1459f19b328c0fc47877e30a5341fdc1ba251ecc",
          "md5": "1cdd5e4c889d2a6aa200f07d511a7a2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "5.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "buildchecks-4.0.4.jar",
          "url": "buildchecks-4.0.4.jar",
          "size": 384859,
          "sha512": "a93119dfe6af4b902ad364f48cb25e9105efe9f0a480793730a0e6a172137b4118a2a89011a8245cbad483f992586661aa1bbf72246b3d348389d683a61e4b17",
          "sha256": "352bd26ca61258123518304928f142b6c1fadef5671cf6c54a41f1a6b5774963",
          "sha1": "1459f19b328c0fc47877e30a5341fdc1ba251ecc",
          "md5": "1cdd5e4c889d2a6aa200f07d511a7a2b"
        }
      ]
    }
  ]
}
