{
  "formatVersion": "1.1",
  "component": {
    "group": "com.toddway",
    "module": "buildchecks",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "buildchecks-4.0.5.jar",
          "url": "buildchecks-4.0.5.jar",
          "size": 385512,
          "sha512": "1a2780d3c911d8e0d36c324992e96088098201ed4057e6c84f894b1cf2271b3db89c80d8e163ca3b2423504f34a4268246457e41bd0b471d6938789588fc563e",
          "sha256": "299bfd767817785c846f63d3d6c5843945d3466640a72b57bd762e3871915ea1",
          "sha1": "1566250c66984318be3477e1510fac51148fc4b4",
          "md5": "724aa5ac84425a27a43f2fdaad9f62bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "5.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "buildchecks-4.0.5.jar",
          "url": "buildchecks-4.0.5.jar",
          "size": 385512,
          "sha512": "1a2780d3c911d8e0d36c324992e96088098201ed4057e6c84f894b1cf2271b3db89c80d8e163ca3b2423504f34a4268246457e41bd0b471d6938789588fc563e",
          "sha256": "299bfd767817785c846f63d3d6c5843945d3466640a72b57bd762e3871915ea1",
          "sha1": "1566250c66984318be3477e1510fac51148fc4b4",
          "md5": "724aa5ac84425a27a43f2fdaad9f62bb"
        }
      ]
    }
  ]
}
